### ISSUE TITLE
Support csscomb.js

### ISSUE THREAD

**Issue by tonyganch** [csscomb/vim-csscomb#6]
We have [a node version of csscomb](https://github.com/csscomb/csscomb.js) ready.
It will be nice if this plugin is updated by the time of public release.

If someone starts working on this task, please leave a comment.
Keep in mind that current (php) version should stay available for download.
The easiest way is [to make a release](https://github.com/csscomb/csscomb-for-vim/releases/new) before making any changes.
Thank you.

**Comment by faceleg** [comment]
See #9 for my PR

**Comment by faceleg** [comment]
This should be closed, @tonyganch?

**Comment by tonyganch** [comment]
@faceleg, yes!
Do you have twitter?

**Comment by faceleg** [comment]
Yep, it's @codeofinterest
